### ISSUE TITLE
Templates page responsive issue

### ISSUE THREAD

**Issue by mahmudunnabikajal** [Asfak00/zenui-library#11]
**Describe the bug**
Templates page responsive design is not working as expected

**To Reproduce**
1. Visit [Templates](https://zenui.net/getting-started/templates) page

**Expected behavior**
Design should be responsive.

**Screenshots**
![image](https://github.com/user-attachments/assets/da8260a3-8013-4944-bc54-44a400f3d00b)

**Desktop**
 - OS: Windows 10
 - Browser Chrome & Brave
 - Screen: 1280px (Common laptop display)

**Comment by Asfak00** [comment]
Everything is perfect check again. Do not increment or decrement screen size via zoom because it's not responsive testing process.

Thank you
