### ISSUE TITLE
Let's create CND API of icon

### ISSUE THREAD

**Issue by nahidhk** [Asfak00/zenui-library#14]
**I have a special request for you. Want to make a specific change, but need your help figuring out which CDN API system might be appropriate for this icon Please inform**

**Comment by Asfak00** [comment]
Thank you for reaching out with your request! I'd be happy to help you find the right CDN API system for your icon needs. Could you provide a bit more detail about the specific change you're looking to make or the type of icons you need? For example, are you looking for a specific icon library like FontAwesome, Material Icons, or a custom solution? This will help me guide you toward the best CDN option!
