### ISSUE TITLE
Add Scrollspy on the component sidebar "Content" options

### ISSUE THREAD

**Issue by Asfak00** [Asfak00/zenui-library#17]
**Is your feature request related to a problem? Please describe.**
The issue arises when scrolling through the content of a webpage with a sidebar containing "Content" options. As the user scrolls through different sections of the page, the corresponding sidebar "Content" options are not dynamically highlighted or marked as active based on the currently visible section. This lack of synchronization between the sections and sidebar options can lead to confusion, as users may not easily know which section they are currently viewing.

**Describe the solution you'd like**
To fix this, you can implement a Scrollspy feature that tracks the scroll position and updates the active state of the sidebar options accordingly.

**Comment by nilaygit-10721** [comment]
can you assign me this issue?

**Comment by Asfak00** [comment]
Yes, sure. I have already been assigned to it. Please check the issue
again.

Thank you for your interest to contribute in ZenUI Library. We hope we will
get something exciting from you soon.

**Comment by danishzayan** [comment]
@Asfak00 Assign me this issue.

**Comment by Asfak00** [comment]
@danishzayan done.

**Comment by danishzayan** [comment]
@Asfak00 

I have fixed this issue. give me some time i will push my code.

**Comment by Asfak00** [comment]
Ok, thanks for the update.

**Comment by danishzayan** [comment]
# Merge Documentation

## Completed Tasks
- [x] Added input contents configuration for all form components
- [x] Implemented scrollspy functionality for navigation
- [x] Created separate content configs for:
  - Text Input
  - File Input 
  - Select Input
  - Checkbox Input
  - Radio Input
  - Strong Password
  - Number Input
  - Range Input
  - OTP Input
  - Switch Input
- [x] Tested scroll highlighting functionality
- [x] Code organized and properly structured

## PR Details
**PR #33** Created for merging: [View Pull Request](https://github.com/Asfak00/zenui-library/pull/33)

### Next Steps
- work in progress for remaining scroll.

### Testing Notes
- Verified scroll behavior across all input components
- Confirmed content highlighting works as expected
- Tested navigation functionality

### loom Video: https://www.loom.com/share/200d0ca0a9724be7bac05eccc54aa3c7?sid=5893863e-ff7e-455e-a0e0-3ffabad08100
