### ISSUE TITLE
Icon page alignment issue

### ISSUE THREAD

**Issue by ahmod001** [Asfak00/zenui-library#18]
**Describe the bug**

It's a small bug inside the Icon page, where we can see all icons. When viewing that page from a mobile device, the icons are displayed one at a time, and the alignment is not centered.

**Expected behavior**

To solve this small issue, we can either show two icons at once in mobile view, or we can display one icon at a time with the position centered. 

In my opinion, showing two icons at once would be more convenient.

**Screenshots**

![image](https://github.com/user-attachments/assets/8d65b299-9f83-4be7-9887-5992fe0c0e52)

**Comment by Asfak00** [comment]
**Issue Update**

The alignment bug on the Icon page in mobile view has been successfully resolved. With the updated layout, icons display correctly.

> Thanks for your patience, and feel free to reopen the issue if any related problems arise.

**Comment by Asfak00** [comment]
**Issue Update**

The alignment bug on the Icon page in mobile view has been successfully resolved. With the updated layout, icons display correctly.

> Thanks for your patience, and feel free to reopen the issue if any related problems arise.
