### ISSUE TITLE
Add more timeling component 

### ISSUE THREAD

**Issue by enoughio** [Asfak00/zenui-library#32]
**Is your feature request related to a problem? Please describe.**
there is a need to add more timeline components 

**Describe the solution you'd like**
 The current UI component library has limited options for timeline components, with only two available types. This limits design flexibility and makes it difficult to accommodate varied use cases that require different timeline styles.

**Describe alternatives you've considered**
I would like an expanded set of timeline components added to the library. This could include variations such as:

Horizontal and vertical timelines with different layout options.
Interactive timelines that support user actions like expanding and collapsing events.
Customizable timelines with different design themes (e.g., minimalistic, detailed, card-based).
Timelines with dynamic data-loading capabilities for real-time updates.

**Additional context**
Expanding the range of timeline components will make the library more versatile and useful for developers looking to create engaging and visually appealing UI experiences.

**Comment by enoughio** [comment]
I have started work on this feature request to expand the timeline component library. I’ll be adding new timeline variations to enhance design options and functionality

please assign it to me.

**Comment by Asfak00** [comment]
You added now!

**Comment by Asfak00** [comment]
> I have started work on this feature request to expand the timeline component library. I’ll be adding new timeline variations to enhance design options and functionality
> 
> please assign it to me.

are you working or not? give me the update!
