### ISSUE TITLE
Avoid components list to scroll to top whenever user choose another component

### ISSUE THREAD

**Issue by Pet3r1512** [Asfak00/zenui-library#41]
**Is your feature request related to a problem? Please describe.**
Whenever I go for components at the end of sidebar (i mean the components list), it will always be scrolled to top when navigating to a new component page

**Describe the solution you'd like**
Keep the components list while users are looking for components

**Comment by eshward95** [comment]
Have raised a PR for this issue please check @Asfak00

**Comment by Asfak00** [comment]
> Have raised a PR for this issue please check @Asfak00

Done. provide your email we will reach out you

**Comment by Asfak00** [comment]
The issue solved. We will update the website very soon.

**Comment by eshward95** [comment]
> > Have raised a PR for this issue please check @Asfak00
> 
> Done. provide your email we will reach out you

eshward95@gmail.com @Asfak00
