### ISSUE TITLE
Smart pagination component

### ISSUE THREAD

**Issue by md-asif-ullah** [Asfak00/zenui-library#54]
**Is your feature request related to a problem? Please describe.**

Navigating large datasets is challenging without a pagination system. Users may experience slow loading times and difficulty accessing specific items.

**Describe the solution you'd like**

Implement a pagination system with:
1.  A fixed number of items per page.
2.  Navigation controls (Next, Previous, and page numbers).
3. API support for pagination parameters like page and limit.
4. Optimization for handling large datasets efficiently.

**Describe alternatives you've considered**
1. Infinite scrolling: Automatically load items as users scroll.
2. Load more button: A button to manually load more items.

**Additional context**

![Screenshot from 2024-11-27 00-26-51](https://github.com/user-attachments/assets/f33d3e33-e4c7-4ace-9842-eb043231ba1a)

**Comment by md-asif-ullah** [comment]
I went to work on this issue, assigned me.

**Comment by Asfak00** [comment]
No worries, you work I'll assign you.
