### ISSUE TITLE
Optimize App.jsx

### ISSUE THREAD

**Issue by Zysd836** [Asfak00/zenui-library#62]
In the App.jsx file, I have identified three main issues that need improvement:

1. Incorrect handling of side effects: The mousemove event is added directly to the document, which is not in line with best practices in React. This approach can lead to memory leaks and make it harder to manage the event listeners. I have also mentioned a similar issue in Pull Request #60.
![image](https://github.com/user-attachments/assets/f2b3f424-7b64-4d87-be32-6c597a16a675)

2. Inefficient state management: The cursorPosition and isMemeVisible states are managed directly within the App component, causing the entire application to re-render continuously when the mousemove event occurs. In reality, these states are only needed by the MemeImage component, so keeping them in the App component is unnecessary and negatively impacts performance.
![image](https://github.com/user-attachments/assets/42e6aedd-7c71-400f-a23e-806ee035b84b)

Proposed Solution: Extract the MemeImage into a separate component, manage the state and event logic independently within it. This will prevent unnecessary re-renders of the entire app, making the App component cleaner and improving performance.

3. Lack of lazy loading for routes: Currently, all routes are imported synchronously, increasing the initial JavaScript payload and unnecessarily delaying page load times. Using React.lazy and Suspense will allow routes to be loaded only when needed, reducing the initial JavaScript load and improving the user experience.
When lazy loading is not implemented, all the code for your application, including routes and components, is bundled into a single JavaScript file. This increases the initial loading time of the application since the entire bundle must be downloaded before anything can be rendered. By using React.lazy() and Suspense, you can split the code into smaller chunks and only load the necessary code for each route when it’s needed, significantly improving the performance of your application
![image](https://github.com/user-attachments/assets/17fe5398-1dc0-4493-801e-bf198f86a6ea)

Let me handle this issues and will submit a Pull Request soon.

Additionally, I have noticed several areas of the project that require refactoring for further optimization. I will create detailed issues in the coming days to propose necessary improvements. Refactoring will take effort, but I believe it is essential for ensuring a more stable and scalable application.

**Comment by Asfak00** [comment]
Thank you for your optimized solution. but right now we don't need to show the meme in the website that's why will remove those codes from the project in upcoming updates.

**Comment by Zysd836** [comment]
I think the issue of switching to using Suspense and React.lazy() is still necessary, as it significantly improves performance
I have measured the performance of the current application, and it is quite low
Before optimized:
![image](https://github.com/user-attachments/assets/cffcc5ce-6cf3-4900-8d72-4140674ee0e1)
After optimized:
![image](https://github.com/user-attachments/assets/2d000456-a09f-4c88-ac06-4a91130d644f)
